name: linux-appimage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: build

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2

    - name: Install project dependencies
      run: |
        npm install -g yarn
        npm install

    - name: Build project
      run: npm run b --verbose

    - name: List build/bin contents
      run: ls -la build/bin

    - name: Build AppImage with electron-builder
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NUMBER: ${{ secrets.BUILD_NUMBER }}
        CUSTOM_UPLOAD_URL: ${{ secrets.CUSTOM_UPLOAD_URL }}
      run: npx electron-builder --linux appimage

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: appimage
        path: |
          dist/*.AppImage
        retention-days: 7
